service: reto-culqui

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

functions:
  card:
    handler: src/functions/card/handler.cardService
    events:
      - http:
          method: POST
          path: /card
  token:
    handler: src/functions/card/handler.tokenService
    events:
      - http:
          method: GET
          path: /token

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    platform: node
    concurrency: 10
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  exclude:
    - node_modules/**
